# Site settings
author: Jodie Sternal
title: Deciding Software Engineering
header-img: img/home-bg.png
email: jodiesternal@yahoo.com
copyright_name: Jodie Sternal
description: > # this means to ignore newlines until "baseurl:"
  Software Engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jodiesternal

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
